name: WolvenKit-Nightly
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest
    - name: Restore packages
      run: nuget restore WolvenKit.sln
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Build with MSBuild
      run: msbuild  WolvenKit.sln -p:Configuration=Release  -p:Platform=x64 -m
    - name: Zip Release
      run: |
        cd $Env:GITHUB_WORKSPACE\\WolvenKit\bin
        Compress-Archive -Path ./Release/ -DestinationPath WolvenKit.zip
    - name: Deploy Nightly
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
      with:
        upload_url: https://uploads.github.com/repos/WolvenKit/WolvenKit-7/releases/68038231/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
        release_id: 68038231
        asset_path: WolvenKit/bin/WolvenKit.zip
        asset_name: WolvenKit-Nightly-$$.zip # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
        asset_content_type: application/zip # required by GitHub API
        max_releases: 5 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
